﻿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head></head><body>


























































<div class="container-fluid main-container">




<div>



<h1 class="title toc-ignore">Dummy Variables Lab</h1>
<h4 class="author">Anthony Restivo</h4>
<h4 class="date">11/2/2025</h4>

</div>


<p><font size="4"></font></p><font size="4">
<hr/>
<div class="section level2">
<h2>Intro</h2>
<p>We will take today’s exercise as an opportunity to learn about how to
estimate the effect of qualitative variables (like a person’s race or
sex, the industry a firm operates in, the state a household or firm is
located in etc) on the dependent variable.</p>
<p>More generally, these variables are known as <strong>categorical
variables</strong> as they reflect information about being in different
categories, like sex, race, state, country, industry, etc, where it
would not be natural to treat those categories in the same way we treat
quantitative variables.</p>
<p>Note that some categorical variables come in the form of binary
information: whether a person self reports as female or male, whether
they have attended college or not, whether they own a computer or not,
whether the firm offers a retirement plan or not, whether a state has
capital punishment or not, etc etc.</p>
<p>Note that the information in these variables can be captured by
defining a <strong>binary variable</strong> also known as a
<strong>dummy variable</strong>, <strong>indicator variable</strong>, or
a <strong>zero-one variable</strong>.</p>
<p>We will start by investigating whether there are differences in wages
across qualitative categories like race and sex.</p>
</div>
<div class="section level2">
<h2>Q0</h2>
<p>We will work with the dataset “wage1” in the Wooldridge package. Make
sure you have the Wooldridge package and other packages you find handy
loaded, I have included some handy ones in the preamble above, take a
moment to load them in.</p>
<p>Once your packages are loaded, assign the Wooldridge dataset “wage1”
to an object named “df” or similar.</p>
<pre class="r"><code>df &lt;- wage1

### the code below will be used to demonstrate how R can handle categorical variables directly
df &lt;- df %&gt;%
  mutate(mf = case_when(grepl(1, female)~&quot;F&quot;, grepl(0,female)~&quot;M&quot;))</code></pre>
</div>
<div class="section level2">
<h2>Q1</h2>
<p>Consider the following regression model:</p>
<p><span class="math display">\[wage_i = \beta_0 + \beta_1 female_i +
\beta_2 nonwhite_i+ \beta_3 educ_i \\ + \beta_4 exper_i +\beta_5
tenure_i+u_i\]</span></p>
<p>where:</p>
<p>female = 1 if individual i is female, and 0 otherwise (male)</p>
<p>nonwhite = 1 if individual is not white, and 0 otherwise (white)</p>
<p>educ = the number of years of education</p>
<p>experience = years of potential experience</p>
<p>tenure = years with current employer</p>
<p>If people never changed jobs then tenure &amp; experience would be
perfectly collinear</p>
<p><strong>Q for chat:</strong> who is the base category? (who has
values of 0 for female indicator and nonwhite indicator?)</p>
<p>A:</p>
<div class="section level3">
<h3>Q1.a</h3>
<p>Q:Estimate the model above, store the results in an object named
“ols1” (or similar) and print the results using summary().</p>
<p>A:</p>
<pre class="r"><code>ols1 &lt;- lm(wage~female+nonwhite+educ+exper+tenure, data=df)
ols1 %&gt;% summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = wage ~ female + nonwhite + educ + exper + tenure, 
##     data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.6623 -1.7842 -0.4355  1.0810 13.9945 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) -1.54030    0.73231  -2.103               0.0359 *  
## female      -1.81204    0.26510  -6.835      0.0000000000230 ***
## nonwhite    -0.11587    0.42692  -0.271               0.7862    
## educ         0.57034    0.04957  11.507 &lt; 0.0000000000000002 ***
## exper        0.02534    0.01158   2.188               0.0291 *  
## tenure       0.14107    0.02118   6.660      0.0000000000698 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.96 on 520 degrees of freedom
## Multiple R-squared:  0.3636, Adjusted R-squared:  0.3575 
## F-statistic: 59.43 on 5 and 520 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<pre class="r"><code>stargazer(ols1,type=&quot;text&quot;)</code></pre>
<pre><code>## 
## ===============================================
##                         Dependent variable:    
##                     ---------------------------
##                                wage            
## -----------------------------------------------
## female                       -1.812***         
##                               (0.265)          
##                                                
## nonwhite                      -0.116           
##                               (0.427)          
##                                                
## educ                         0.570***          
##                               (0.050)          
##                                                
## exper                         0.025**          
##                               (0.012)          
##                                                
## tenure                       0.141***          
##                               (0.021)          
##                                                
## Constant                     -1.540**          
##                               (0.732)          
##                                                
## -----------------------------------------------
## Observations                    526            
## R2                             0.364           
## Adjusted R2                    0.358           
## Residual Std. Error      2.960 (df = 520)      
## F Statistic           59.427*** (df = 5; 520)  
## ===============================================
## Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<div class="section level3">
<h3>Q1.b</h3>
<p>Show the students how to use the as.factor and relevel function to
work with categorical variables in R when they are entered as
strings.</p>
<pre class="r"><code>lm(wage~as.factor(mf),data=df) %&gt;% summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = wage ~ as.factor(mf), data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.5995 -1.8495 -0.9877  1.4260 17.8805 
## 
## Coefficients:
##                Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)      4.5877     0.2190  20.950 &lt; 0.0000000000000002 ***
## as.factor(mf)M   2.5118     0.3034   8.279  0.00000000000000104 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.476 on 524 degrees of freedom
## Multiple R-squared:  0.1157, Adjusted R-squared:  0.114 
## F-statistic: 68.54 on 1 and 524 DF,  p-value: 0.000000000000001042</code></pre>
<pre class="r"><code>df$mf &lt;-relevel(factor(df$mf), ref=&quot;M&quot;)

lm(wage~as.factor(mf),data=df) %&gt;% summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = wage ~ as.factor(mf), data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.5995 -1.8495 -0.9877  1.4260 17.8805 
## 
## Coefficients:
##                Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)      7.0995     0.2100  33.806 &lt; 0.0000000000000002 ***
## as.factor(mf)F  -2.5118     0.3034  -8.279  0.00000000000000104 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.476 on 524 degrees of freedom
## Multiple R-squared:  0.1157, Adjusted R-squared:  0.114 
## F-statistic: 68.54 on 1 and 524 DF,  p-value: 0.000000000000001042</code></pre>
<hr/>
</div>
</div>
<div class="section level2">
<h2>Q2</h2>
<p>Using your results from Q1, calculate the following the expected
value of wage conditional on the given information in each problem.</p>
<pre class="r"><code>stargazer(ols1,type=&quot;text&quot;)</code></pre>
<pre><code>## 
## ===============================================
##                         Dependent variable:    
##                     ---------------------------
##                                wage            
## -----------------------------------------------
## female                       -1.812***         
##                               (0.265)          
##                                                
## nonwhite                      -0.116           
##                               (0.427)          
##                                                
## educ                         0.570***          
##                               (0.050)          
##                                                
## exper                         0.025**          
##                               (0.012)          
##                                                
## tenure                       0.141***          
##                               (0.021)          
##                                                
## Constant                     -1.540**          
##                               (0.732)          
##                                                
## -----------------------------------------------
## Observations                    526            
## R2                             0.364           
## Adjusted R2                    0.358           
## Residual Std. Error      2.960 (df = 520)      
## F Statistic           59.427*** (df = 5; 520)  
## ===============================================
## Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<pre class="r"><code>coefs1 &lt;- summary(ols1)$coefficients[]
coefs1</code></pre>
<pre><code>##                Estimate Std. Error    t value
## (Intercept) -1.54029811 0.73231151 -2.1033373
## female      -1.81204294 0.26509726 -6.8353892
## nonwhite    -0.11587403 0.42691794 -0.2714199
## educ         0.57034217 0.04956666 11.5065684
## exper        0.02534303 0.01158137  2.1882589
## tenure       0.14106975 0.02118186  6.6599308
##                                        Pr(&gt;|t|)
## (Intercept) 0.035916101614480874792967313169356
## female      0.000000000022981606280892390528105
## nonwhite    0.786175799217779691652197016082937
## educ        0.000000000000000000000000001878803
## exper       0.029094951623982161920123346021683
## tenure      0.000000000069837850617509081956047</code></pre>
<pre class="r"><code>coefs1[&quot;female&quot; ,1]</code></pre>
<pre><code>## [1] -1.812043</code></pre>
<pre class="r"><code>coefs1[&quot;nonwhite&quot; ,1]</code></pre>
<pre><code>## [1] -0.115874</code></pre>
<div class="section level3">
<h3>Q2.a</h3>
<p>Interpret the coefficient on female and nonwhite.</p>
<p>A: All else equal, a females hourly wage is $ 1.8120 less than male’s
hourly wage. This effect is statistically significant at the
conventional significance levels.</p>
<p>All else equal, a nonwhite hourly wage is $ 0.1159 lower than a white
individual’s wage.</p>
</div>
<div class="section level3">
<h3>Q2.b</h3>
<p>Expected wages for a white female with average education, experience,
and tenure.</p>
<pre class="r"><code>pred_1&lt;-
data.frame(female=1,nonwhite=0,educ=mean(df$educ),exper=mean(df$exper),tenure=mean(df$tenure)) 
pred_1wage&lt;-
predict(ols1,pred_1)</code></pre>
<p>A: The predicted wage for a white female for the average education
experience in tenure is$ 4.9641 per hour.</p>
</div>
<div class="section level3">
<h3>Q2.c</h3>
<p>Expected wages for a white male with average education, experience,
and tenure.</p>
<pre class="r"><code>pred_1&lt;-
data.frame(male=1,nonwhite=0,educ=mean(df$educ),exper=mean(df$exper),tenure=mean(df$tenure)) 

pred_1</code></pre>
<pre><code>##   male nonwhite     educ    exper   tenure
## 1    1        0 12.56274 17.01711 5.104563</code></pre>
<p>A: The predicted wage for a white male for the average experience in
tenure is 5.104563</p>
</div>
<div class="section level3">
<h3>Q2.</h3>
<p>Expected wages for a nonwhite female with average education,
experience, and tenure.</p>
<pre class="r"><code>pred_1&lt;-
data.frame(female=1,nonwhite=1,educ=mean(df$educ),exper=mean(df$exper),tenure=mean(df$tenure)) 
pred_1</code></pre>
<pre><code>##   female nonwhite     educ    exper   tenure
## 1      1        1 12.56274 17.01711 5.104563</code></pre>
<pre class="r"><code>predict(ols1,pred_1)</code></pre>
<pre><code>##        1 
## 4.848209</code></pre>
<p>A:The predicted wage for a nonwhite female fro the average experience
in tenure is 4.848209</p>
</div>
<div class="section level3">
<h3>Q2.e</h3>
<p>Expected wages for a nonwhite male with average education,
experience, and tenure.</p>
<pre class="r"><code>pred_1&lt;-
data.frame(male=1,nonwhite=1,educ=mean(df$educ),exper=mean(df$exper),tenure=mean(df$tenure))

pred_1</code></pre>
<pre><code>##   male nonwhite     educ    exper   tenure
## 1    1        1 12.56274 17.01711 5.104563</code></pre>
<p>A: The predicted wage for a nonwhite male from the average experience
in tenure is 5.104563</p>
</div>
</div>
<div class="section level2">
<h2>Q3</h2>
<p><span class="math display">\[wage_i = \beta_0 + \beta_1 female_i +
\beta_2 nonwhite_i+ \beta_3 educ_i \\ + \beta_4 exper_i +\beta_5
tenure_i+u_i\]</span></p>
<p>Consider the formal hypothesis test that, for otherwise identical
individuals, a female’s hourly wage is different from a male’s hourly
wage.</p>
<p>null: no difference in hourly wages alternative: there is a
difference in hourly wages</p>
<div class="section level3">
<h3>Q3.a</h3>
<p>Specify the null and alternative hypothesis for the hypothesis test
above</p>
<p>Null Hypothesis - <span class="math inline">\(H_O:\beta_1
=0\)</span></p>
<p>Alternative Hypothesis - <span class="math inline">\(H_A: \beta_1
\neq0\)</span></p>
</div>
<div class="section level3">
<h3>Q3.b</h3>
<p>Use the summary() function on your regression results to find the
following:</p>
<pre class="r"><code>coefs1</code></pre>
<pre><code>##                Estimate Std. Error    t value
## (Intercept) -1.54029811 0.73231151 -2.1033373
## female      -1.81204294 0.26509726 -6.8353892
## nonwhite    -0.11587403 0.42691794 -0.2714199
## educ         0.57034217 0.04956666 11.5065684
## exper        0.02534303 0.01158137  2.1882589
## tenure       0.14106975 0.02118186  6.6599308
##                                        Pr(&gt;|t|)
## (Intercept) 0.035916101614480874792967313169356
## female      0.000000000022981606280892390528105
## nonwhite    0.786175799217779691652197016082937
## educ        0.000000000000000000000000001878803
## exper       0.029094951623982161920123346021683
## tenure      0.000000000069837850617509081956047</code></pre>
<pre class="r"><code>coefs1[&quot;female&quot;,&quot;t value&quot;]</code></pre>
<pre><code>## [1] -6.835389</code></pre>
<pre class="r"><code>coefs1[&quot;female&quot;,&quot;Pr(&gt;|t|)&quot;]</code></pre>
<pre><code>## [1] 0.00000000002298161</code></pre>
<ol style="list-style-type: lower-roman;">
<li>The t-statistic for the hypothesis test above.</li>
</ol>
<p>A: The T statistic for the two sided alternative test above is
-6.8354</p>
<ol start="2" style="list-style-type: lower-roman;">
<li>The p-value associated with the t-statistic above.</li>
</ol>
<p>A: The P value for the two sided alternative test above is &lt;
0.0000</p>
</div>
<div class="section level3">
<h3>Q3.c</h3>
<p>Formally report the conclusion you reach regarding this hypothesis in
Q3 at the <span class="math inline">\(\alpha=0.05\)</span> significance
level (5% significance level).</p>
<p>A: We reject the null hypothesis and we can conclude that the wage
between the genders male and female are not the same.</p>
</div>
<div class="section level3">
<h3>Q3.d</h3>
<p>Do you think your results here indicate that there is a wage gap
based on gender?</p>
<p>Hint - think about whether your estimated effect here is an unbiased
estimate of the effect of gender on wages, or whether there are omitted
variables that are correlated with wages and gender that should be
included in the model. Make an argument for whichever you believe to be
the case.</p>
<p>A: Yes there is a wage gap as we can see from the estimates the
females earn less than the males. However there possibly could be
omitted variables present which would have a major impact on wages
within the gender.</p>
</div>
</div>
<div class="section level2">
<h2>Q4</h2>
<p><span class="math display">\[wage_i = \beta_0 + \beta_1 female_i +
\beta_2 nonwhite_i+ \beta_3 educ_i \\ + \beta_4 exper_i +\beta_5
tenure_i+u_i\]</span></p>
<p>Consider the formal hypothesis test that, for otherwise identical
individuals, a white individual’s wage is different from a nonwhite
individuals hourly wage.</p>
<div class="section level3">
<h3>Q4.a</h3>
<p>Specify the null and alternative hypothesis for the hypothesis test
above</p>
<p>Null Hypothesis - <span class="math inline">\(H_O:\beta_2=0\)</span></p>
<p>Alternative Hypothesis - <span class="math inline">\(H_A:\beta_2
\neq0\)</span></p>
</div>
<div class="section level3">
<h3>Q4.b</h3>
<p>Use the summary() function on your regression results to find the
following:</p>
<pre class="r"><code>coefs1</code></pre>
<pre><code>##                Estimate Std. Error    t value
## (Intercept) -1.54029811 0.73231151 -2.1033373
## female      -1.81204294 0.26509726 -6.8353892
## nonwhite    -0.11587403 0.42691794 -0.2714199
## educ         0.57034217 0.04956666 11.5065684
## exper        0.02534303 0.01158137  2.1882589
## tenure       0.14106975 0.02118186  6.6599308
##                                        Pr(&gt;|t|)
## (Intercept) 0.035916101614480874792967313169356
## female      0.000000000022981606280892390528105
## nonwhite    0.786175799217779691652197016082937
## educ        0.000000000000000000000000001878803
## exper       0.029094951623982161920123346021683
## tenure      0.000000000069837850617509081956047</code></pre>
<pre class="r"><code>coefs1[&quot;nonwhite&quot;,&quot;t value&quot;]</code></pre>
<pre><code>## [1] -0.2714199</code></pre>
<pre class="r"><code>coefs1[&quot;nonwhite&quot;,&quot;Pr(&gt;|t|)&quot;]</code></pre>
<pre><code>## [1] 0.7861758</code></pre>
<ol style="list-style-type: lower-roman;">
<li>The t-statistic for the hypothesis test above.</li>
</ol>
<p>A: The T statistic for the two sided alternative test above is
-0.2714</p>
<ol start="2" style="list-style-type: lower-roman;">
<li>The p-value associated with the t-statistic above.</li>
</ol>
<p>A: The p value associated with the t-statistic for the two sided
alternative test above is 0.7862</p>
</div>
<div class="section level3">
<h3>Q4.d</h3>
<p>Formally report the conclusion you reach regarding this hypothesis in
Q4 at the <span class="math inline">\(\alpha=0.05\)</span> significance
level (5% significance level).</p>
<p>A: We fail to reject the null hypothesis. There’s not a wage gap
between white an nonwhite individuals.</p>
</div>
</div>
<div class="section level2">
<h2>Q5</h2>
<p>Let’s explore the use of dummy variables to allow for the slope
parameters to differ across groups.</p>
<p>Consider a model that includes <strong>interactions</strong> between
the qualitative variable <em>female</em> and the quantitative variable
<em>exper</em>.</p>
<p>This will allow us to examine whether the returns to experience are
the same for males and females.</p>
<p><span class="math display">\[wage_i=\beta_0 + \beta_1 female_i +
\beta_2 nonwhite_i+ \beta_3 educ_i + \\ + \beta_4 exper_i +\beta_5
exper_i\times female_i\\+\beta_6 tenure_i + u_i\]</span> Notice that for
this model, if <span class="math inline">\(\beta_5\neq0\)</span>, the
partial effect of experience depends on whether the individual is
female: <span class="math display">\[\frac{\partial wage}{\partial
exper}=\beta_4+\beta_5 female_i\]</span> meaning that if the individual
is male (female = 0) the return to experience is: <span class="math display">\[\frac{\partial wage}{\partial
exper}=\beta_4+\beta_5\times (0)\\=\beta_4\]</span> while if the
individual is female (female=1), the return to experience is <span class="math display">\[\frac{\partial wage}{\partial
exper}=\beta_4+\beta_5\times(1)\\=\beta_4+\beta_5\]</span> and these are
different from each other so long as <span class="math inline">\(\beta_5\neq0\)</span>.</p>
<p>Estimate the model above, store the results in an object named “ols2”
(or similar), and print the results along with your output from Q1.a
using the stargazer package.</p>
<pre class="r"><code>ols2 &lt;- lm(wage~female+nonwhite+educ+exper+exper:female+tenure,data=df) 
stargazer(ols2,type=&quot;text&quot;)</code></pre>
<pre><code>## 
## ===============================================
##                         Dependent variable:    
##                     ---------------------------
##                                wage            
## -----------------------------------------------
## female                       -0.879**          
##                               (0.416)          
##                                                
## nonwhite                      -0.107           
##                               (0.424)          
##                                                
## educ                         0.588***          
##                               (0.050)          
##                                                
## exper                        0.057***          
##                               (0.016)          
##                                                
## tenure                       0.128***          
##                               (0.022)          
##                                                
## female:exper                 -0.056***         
##                               (0.019)          
##                                                
## Constant                     -2.248***         
##                               (0.767)          
##                                                
## -----------------------------------------------
## Observations                    526            
## R2                             0.374           
## Adjusted R2                    0.366           
## Residual Std. Error      2.939 (df = 519)      
## F Statistic           51.621*** (df = 6; 519)  
## ===============================================
## Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<pre class="r"><code>coefs2 &lt;- summary(ols2)$coefficients[]
coefs2[&quot;exper&quot;,&quot;Estimate&quot;]</code></pre>
<pre><code>## [1] 0.05713069</code></pre>
<div class="section level3">
<h3>Q5.a</h3>
<p>Based on your estimates, what is the expected increase in hourly
wages for an additional 10 years experience for a male and for a
female?</p>
<p>A: For an additional 10 years of experience for a male, their hourly
wage is expected to increase $0.5713 per hour. An otherwise identical
female will have their hourly wages increase by $0.0082 per hour.</p>
</div>
<div class="section level3">
<h3>Q5.b</h3>
<p>How is this estimate different from the expected increase in hourly
wages for an additional 10 years experience based on your estimates from
the model in Q1?</p>
<p>A: In q1 there wasn’t a difference from hourly wages from male’s and
female’s. Although q5 their is a difference with the return to
experience for male’s and female’s.</p>
</div>
<div class="section level3">
<h3>Q5.c</h3>
<p>Specify the null and alternative hypothesis for a test that the
return to experience is the same for the sexes against the alternative
that the return to experience is different across the sexes.</p>
<p>Null hypothesis - <span class="math inline">\(H_O:
\beta_5=0\)</span></p>
<p>Alternative hypothesis - <span class="math inline">\(H_A: \beta_5
\neq0\)</span></p>
</div>
<div class="section level3">
<h3>Q5.d</h3>
<p>Address the following…</p>
<pre class="r"><code>coefs2</code></pre>
<pre><code>##                 Estimate Std. Error    t value
## (Intercept)  -2.24757656 0.76714647 -2.9297881
## female       -0.87937105 0.41612940 -2.1132154
## nonwhite     -0.10663341 0.42393450 -0.2515328
## educ          0.58846198 0.04961555 11.8604350
## exper         0.05713069 0.01590310  3.5924258
## tenure        0.12816338 0.02150087  5.9608457
## female:exper -0.05630851 0.01945763 -2.8939041
##                                           Pr(&gt;|t|)
## (Intercept)  0.00354120797948440091396093976072734
## female       0.03505902967001624931375758364993089
## nonwhite     0.80150180768210976811616319537279196
## educ         0.00000000000000000000000000007036272
## exper        0.00035879347521704609870474289579079
## tenure       0.00000000463891495366764644364340753
## female:exper 0.00396485267582082599735482375535867</code></pre>
<pre class="r"><code>coefs2[&quot;exper&quot;,&quot;t value&quot;]</code></pre>
<pre><code>## [1] 3.592426</code></pre>
<pre class="r"><code>coefs2[&quot;exper&quot;,&quot;Pr(&gt;|t|)&quot;]</code></pre>
<pre><code>## [1] 0.0003587935</code></pre>
<ol style="list-style-type: lower-roman;">
<li>The t-statistic associated with your hypothesis test in Q5C.</li>
</ol>
<p>A: The T statistic for the two sided alternative test above is
3.5924.</p>
<ol start="2" style="list-style-type: lower-roman;">
<li>The p-value associated with the t-statistic above.</li>
</ol>
<p>A: The p value associated with the t-statistic for the two sided
alternative test above is 0.0004.</p>
<ol start="3" style="list-style-type: lower-roman;">
<li>Reach a formal conclusion to your hypothesis test (at the 5%
significance level) in Q5B using your preferred method (critical values,
p, and communicate your conclusion formally below.</li>
</ol>
<p>A: We reject the null hypothesis. We can conclude the return to
experience is NOT the same for males and females. </p>
</div>
</div></font>




</div>















<script type="module" src="https://s.brightspace.com/lib/bsi/2025.12.237/unbundled/mathjax.js"></script><script type="text/javascript">document.addEventListener('DOMContentLoaded', function() {
						if (document.querySelector('math, .d2l-element, .d2l-cplus-layout') || /\$\$|\\\(|\\\[|\\begin{|\\ref{|\\eqref{/.test(document.body.innerHTML)) {
							document.querySelectorAll('mspace[linebreak="newline"]').forEach(elm => {
								elm.setAttribute('style', 'display: block; height: 0.5rem;');
							});

							document.querySelectorAll('math mmultiscripts > none').forEach(elm => {
								const mrow = document.createElementNS('http://www.w3.org/1998/Math/MathML', 'mrow');
								elm.replaceWith(mrow);
							});

							window.D2L.MathJax.loadMathJax({
								outputScale: 1,
								renderLatex: true,
								enableMML3Support: false
							});
						}
					});</script><script type="module" src="https://s.brightspace.com/lib/bsi/2025.12.237/unbundled/prism.js"></script><script type="text/javascript">document.addEventListener('DOMContentLoaded', function() {
					document.querySelectorAll('.d2l-code').forEach(code => {
						window.D2L.Prism.formatCodeElement(code);
					});
				});</script><script type="module" src="https://s.brightspace.com/lib/bsi/2025.12.237/unbundled/embeds.js"></script><script type="text/javascript">document.addEventListener('DOMContentLoaded', function() {
					window.D2L.EmbedRenderer.renderEmbeds(document.body);
				});</script></body></html>